language: node_js
node_js:
  - "node"
  - "iojs"
after_script:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 191a895846ac9a5a25bb28e3620358918674565b9232f386d126dd6be4b3ad45
